xiwi: Patch dummy driver to fix missing ChangeWindowProperty symbol.
Xorg xserver commit eb36924ead40564325aa56d54a973dc8fb4eae83
(git://anongit.freedesktop.org/xorg/xserver) removes the
ChangeWindowProperty function, breaking xf86-video-dummy 0.3.7.  This pulls
in xf86-video-dummy commit 8706f60ab457867c120dd44e812b8fadc2be7179
(git://anongit.freedesktop.org/xorg/driver/xf86-video-dummy) to use the
dixChangeWindowProperty function instead.

diff --git a/targets/xiwi b/targets/xiwi
--- a/targets/xiwi
+++ b/targets/xiwi
@@ -62,6 +62,26 @@ install --minimal --asdeps patch gcc libc-dev pkg-config \
     # -m prevents "time stamp is in the future" spam
     tar --strip-components=1 -xmf dummy.tar.gz
 
+    echo "Patching Xorg dummy driver (fix missing symbol)..." 1>&2
+    patch -p1 <<EOF
+diff --git a/src/dummy_driver.c b/src/dummy_driver.c
+index 470e125..9d4d5bf 100644
+--- a/src/dummy_driver.c
++++ b/src/dummy_driver.c
+@@ -790,8 +790,9 @@ DUMMYCreateWindow(WindowPtr pWin)
+         if (! ValidAtom(VFB_PROP))
+             VFB_PROP = MakeAtom(VFB_PROP_NAME, strlen(VFB_PROP_NAME), 1);
+ 
+-        ret = ChangeWindowProperty(pWinRoot, VFB_PROP, XA_STRING, 
+-		8, PropModeReplace, (int)4, (pointer)"TRUE", FALSE);
++        ret = dixChangeWindowProperty(serverClient, pWinRoot, VFB_PROP,
++                                      XA_STRING, 8, PropModeReplace,
++                                      (int)4, (pointer)"TRUE", FALSE);
+ 	if( ret != Success)
+ 		ErrorF("Could not set VFB root window property");
+         dPtr->prop = TRUE;
+EOF
+
     echo "Patching Xorg dummy driver (xrandr 1.2 support)..." 1>&2
     patch -p1 <<EOF
 diff --git a/src/dummy_driver.c b/src/dummy_driver.c
